<?php
/**
 * Created by PhpStorm.
 * User: scofie
 * Date: 6/7/17
 * Time: 3:30 PM
 */

namespace App\Http\Controllers\Swagger\Contract;


class JZQ
{
    /**
     * @SWG\Post(
     *   path="/contract/index?random=JZQ_ping",
     *   tags={"JZQ:君子签章合同接口"},
     *   summary="ping测试服务可用性",
     *    @SWG\Parameter(
     *      name="secret_sign",
     *      in="formData",
     *      description="数据校验",
     *      required=true,
     *      type="string",
     *      default="b926ab99d913f7bacbb3e526ebf75c98"
     *   ),
     *   @SWG\Parameter(
     *      name="driver",
     *      in="formData",
     *      description="合同渠道",
     *      required=true,
     *      type="string",
     *      default="JZQ",
     *   ),
     *   @SWG\Parameter(
     *      name="method",
     *      in="formData",
     *      description="接口名称",
     *      required=true,
     *      type="string",
     *      default="ping",
     *   ),
     *   @SWG\Response(
     *     response=200,
     *     description="测试服务可用性",
     *   )
     * )
     */
    public function ping(){}

    /**
     * @SWG\Post(
     *   path="/contract/index?random=JZQ_doUpdateApplySignFile",
     *   tags={"JZQ:君子签章合同接口"},
     *   summary="创建君子签的合同",
     *     @SWG\Parameter(
     *      name="driver",
     *      in="formData",
     *      description="合同服务商",
     *      required=true,
     *      type="string",
     *      default="JZQ",
     *   ),
     *   @SWG\Parameter(
     *      name="method",
     *      in="formData",
     *      description="接口名称",
     *      required=true,
     *      type="string",
     *     default="doUpdateApplySignFile",
     *   ),
     *   @SWG\Parameter(
     *      name="contract_name",
     *      in="formData",
     *      description="合同名称",
     *      required=true,
     *      type="string",
     *      default="九斗鱼投资协议132519-1894-196645.pdf",
     *   ),
     *    @SWG\Parameter(
     *      name="contractAmount",
     *      in="formData",
     *      description="合同金额",
     *      required=true,
     *      type="string",
     *      default="100"
     *   ),
     *   @SWG\Parameter(
     *      name="real_name",
     *      in="formData",
     *      description="用户真实姓名",
     *      required=true,
     *      type="string",
     *      default="吴长明",
     *   ),
     *   @SWG\Parameter(
     *      name="identity_card",
     *      in="formData",
     *      description="身份证号",
     *      required=true,
     *      type="string",
     *      default="320323198512134216",
     *   ),
     *     @SWG\Parameter(
     *      name="cash",
     *      in="formData",
     *      description="合同金额",
     *      required=true,
     *      type="string",
     *      default="100",
     *   ),
     *   @SWG\Parameter(
     *      name="phone",
     *      in="formData",
     *      description="手机号",
     *      required=true,
     *      type="string",
     *      default="15701288783",
     *   ),
     *   @SWG\Parameter(
     *      name="page",
     *      in="formData",
     *      description="页数",
     *      required=true,
     *      type="string",
     *      default="3",
     *   ),
     *   @SWG\Parameter(
     *      name="file_path",
     *      in="formData",
     *      description="保全文件路径",
     *      required=true,
     *      type="string",
     *      default="/test/九斗鱼-投资咨询与管理服务协议289946-3861-325610.pdf",
     *   ),
     *   @SWG\Response(
     *     response=200,
     *     description="创建保全",
     *   )
     * )
     */
    public function doUpdateApplySignFile(){}

    /**
     * @SWG\Post(
     *   path="/contract/index?random=JZQ_certificateLinkGet",
     *   tags={"JZQ:君子签章合同接口"},
     *   summary="保全证书的证书链接",
     *    @SWG\Parameter(
     *      name="secret_sign",
     *      in="formData",
     *      description="数据校验",
     *      required=true,
     *      type="string",
     *      default="b926ab99d913f7bacbb3e526ebf75c98"
     *   ),
     *   @SWG\Parameter(
     *      name="driver",
     *      in="formData",
     *      description="合同渠道",
     *      required=true,
     *      type="string",
     *      default="JZQ",
     *   ),
     *   @SWG\Parameter(
     *      name="method",
     *      in="formData",
     *      description="接口名称",
     *      required=true,
     *      type="string",
     *     default="certificateLinkGet",
     *   ),
     *   @SWG\Parameter(
     *      name="apply_no",
     *      in="formData",
     *      description="保全编号",
     *      required=true,
     *      type="string",
     *      default="",
     *   ),
     *   @SWG\Response(
     *     response=200,
     *     description="保全证书的证书链接",
     *   )
     * )
     */
    public function certificateLinkGet(){}
    /**
     * @SWG\Post(
     *   path="/contract/index?random=JZQ_cfDownloadUrl",
     *   tags={"JZQ:君子签章合同接口"},
     *   summary="获取合同保全文件下载地址",
     *    @SWG\Parameter(
     *      name="secret_sign",
     *      in="formData",
     *      description="数据校验",
     *      required=true,
     *      type="string",
     *      default="b926ab99d913f7bacbb3e526ebf75c98"
     *   ),
     *   @SWG\Parameter(
     *      name="driver",
     *      in="formData",
     *      description="合同渠道",
     *      required=true,
     *      type="string",
     *      default="JZQ",
     *   ),
     *   @SWG\Parameter(
     *      name="method",
     *      in="formData",
     *      description="接口名称",
     *      required=true,
     *      type="string",
     *     default="cfDownloadUrl",
     *   ),
     *     @SWG\Parameter(
     *      name="real_name",
     *      in="formData",
     *      description="姓名",
     *      required=true,
     *      type="string",
     *      default="",
     *   ),
     *     @SWG\Parameter(
     *      name="identity_card",
     *      in="formData",
     *      description="身份证号",
     *      required=true,
     *      type="string",
     *      default="",
     *   ),
     *   @SWG\Parameter(
     *      name="apply_no",
     *      in="formData",
     *      description="保全编号",
     *      required=true,
     *      type="string",
     *      default="",
     *   ),
     *   @SWG\Response(
     *     response=200,
     *     description="获取合同保全文件下载地址",
     *   )
     * )
     */
    public function cfDownloadUrl(){}

    /**
     * @SWG\Post(
     *   path="/contract/index?random=JZQ_getSignStatus",
     *   tags={"JZQ:君子签章合同接口"},
     *   summary="根据保全编号查询保全",
     *    @SWG\Parameter(
     *      name="secret_sign",
     *      in="formData",
     *      description="数据校验",
     *      required=true,
     *      type="string",
     *      default="b926ab99d913f7bacbb3e526ebf75c98"
     *   ),
     *   @SWG\Parameter(
     *      name="driver",
     *      in="formData",
     *      description="合同渠道",
     *      required=true,
     *      type="string",
     *      default="JZQ",
     *   ),
     *   @SWG\Parameter(
     *      name="method",
     *      in="formData",
     *      description="接口名称",
     *      required=true,
     *      type="string",
     *     default="getSignStatus",
     *   ),
     *   @SWG\Parameter(
     *      name="apply_no",
     *      in="formData",
     *      description="保全编号",
     *      required=true,
     *      type="string",
     *      default="",
     *   ),
     *     @SWG\Parameter(
     *      name="real_name",
     *      in="formData",
     *      description="姓名",
     *      required=true,
     *      type="string",
     *      default="",
     *   ),
     *     @SWG\Parameter(
     *      name="identity_card",
     *      in="formData",
     *      description="身份证号",
     *      required=true,
     *      type="string",
     *      default="",
     *   ),
     *   @SWG\Response(
     *     response=200,
     *     description="根据保全编号查询保全",
     *   )
     * )
     */
    public function getSignStatus(){}

    /**
     * @SWG\Post(
     *   path="/contract/index?random=JZQ_getSignLink",
     *   tags={"JZQ:君子签章合同接口"},
     *   summary="获取签约的地址链接",
     *   @SWG\Parameter(
     *      name="driver",
     *      in="formData",
     *      description="合同渠道",
     *      required=true,
     *      type="string",
     *      default="JZQ",
     *   ),
     *   @SWG\Parameter(
     *      name="method",
     *      in="formData",
     *      description="接口名称",
     *      required=true,
     *      type="string",
     *     default="getSignLink",
     *   ),
     *   @SWG\Parameter(
     *      name="apply_no",
     *      in="formData",
     *      description="签约编号",
     *      required=true,
     *      type="string",
     *      default="APL872390160803827712",
     *   ),
     *    @SWG\Parameter(
     *      name="real_name",
     *      in="formData",
     *      description="用户名称",
     *      required=true,
     *      type="string",
     *      default="吴长明"
     *   ),
     *   @SWG\Parameter(
     *      name="identity_card",
     *      in="formData",
     *      description="身份证号码",
     *      required=true,
     *      type="string",
     *      default="320323198512134216",
     *   ),
     *   @SWG\Response(
     *     response=200,
     *     description="保全证书的证书链接",
     *   )
     * )
     */
    public function getSignLink(){}

    /**
     * @SWG\Post(
     *   path="/contract/index?random=JZQ_cfViewUrl",
     *   tags={"JZQ:君子签章合同接口"},
     *   summary="获取合同查看页URL",
     *   @SWG\Parameter(
     *      name="partner_id",
     *      in="formData",
     *      description="商户号",
     *      required=true,
     *      type="string",
     *      default="100000178",
     *   ),
     *    @SWG\Parameter(
     *      name="secret_sign",
     *      in="formData",
     *      description="数据校验",
     *      required=true,
     *      type="string",
     *      default="b926ab99d913f7bacbb3e526ebf75c98"
     *   ),
     *   @SWG\Parameter(
     *      name="driver",
     *      in="formData",
     *      description="合同渠道",
     *      required=true,
     *      type="string",
     *      default="JZQ",
     *   ),
     *   @SWG\Parameter(
     *      name="method",
     *      in="formData",
     *      description="接口名称",
     *      required=true,
     *      type="string",
     *     default="cfViewUrl",
     *   ),
     *   @SWG\Parameter(
     *      name="preservation_id",
     *      in="formData",
     *      description="保全编号",
     *      required=true,
     *      type="string",
     *      default="427402",
     *   ),
     *   @SWG\Response(
     *     response=200,
     *     description="获取合同查看页URL",
     *   )
     * )
     */
    public function cfViewUrl(){}

    /**
     * @SWG\Post(
     *   path="/contract/index?random=JZQ_getSignNotify",
     *   tags={"JZQ:君子签章合同接口"},
     *   summary="根据保全编号查询保全用户的确认状态",
     *   @SWG\Parameter(
     *      name="partner_id",
     *      in="formData",
     *      description="商户号",
     *      required=true,
     *      type="string",
     *      default="100000178",
     *   ),
     *    @SWG\Parameter(
     *      name="secret_sign",
     *      in="formData",
     *      description="数据校验",
     *      required=true,
     *      type="string",
     *      default="b926ab99d913f7bacbb3e526ebf75c98"
     *   ),
     *   @SWG\Parameter(
     *      name="driver",
     *      in="formData",
     *      description="合同渠道",
     *      required=true,
     *      type="string",
     *      default="JZQ",
     *   ),
     *   @SWG\Parameter(
     *      name="method",
     *      in="formData",
     *      description="接口名称",
     *      required=true,
     *      type="string",
     *     default="contractStatusGet",
     *   ),
     *   @SWG\Parameter(
     *      name="preservation_id",
     *      in="formData",
     *      description="保全编号",
     *      required=true,
     *      type="string",
     *      default="427402",
     *   ),
     *   @SWG\Response(
     *     response=200,
     *     description="根据保全编号查询保全用户的确认状态",
     *   )
     * )
     */
    public function getSignNotify(){}
}
