<?php
/**
 * Created by PhpStorm.
 * User: zhangshuang
 * Date: 16/6/4
 * Time: 11:16
 */

namespace App\Http\Controllers\Swagger\Pay;

class LLAuth{

    /**
     * @SWG\Post(
     *   path="/recharge/index?random=LLAuth_encrypt",
     *   tags={"LLAuth"},
     *   summary="连连认证支付加密",
     *   @SWG\Parameter(
     *      name="partner_id",
     *      in="formData",
     *      description="商户号",
     *      required=true,
     *      type="string",
     *      default="110000901001",
     *   ),
     *    @SWG\Parameter(
     *      name="secret_sign",
     *      in="formData",
     *      description="数据校验",
     *      required=true,
     *      type="string",
     *     default="b926ab99d913f7bacbb3e526ebf75c98"
     *   ),
     *   @SWG\Parameter(
     *      name="driver",
     *      in="formData",
     *      description="支付渠道(连连认证支付)",
     *      required=true,
     *      type="string",
     *      default="LLAuth",
     *   ),
     *   @SWG\Parameter(
     *      name="method",
     *      in="formData",
     *      description="接口名称(加密)",
     *      required=true,
     *      type="string",
     *     default="encrypt",
     *   ),
     *    @SWG\Parameter(
     *      name="order_id",
     *      in="formData",
     *      description="订单编号",
     *      required=true,
     *      type="string",
     *   ),
     *    @SWG\Parameter(
     *      name="cash",
     *      in="formData",
     *      description="充值金额",
     *      required=true,
     *      type="integer",
     *   ),
     *   @SWG\Parameter(
     *      name="card_no",
     *      in="formData",
     *      description="银行卡号",
     *      required=true,
     *      type="string",
     *   ),
     *   @SWG\Parameter(
     *      name="id_card",
     *      in="formData",
     *      description="身份证号",
     *      required=true,
     *      type="string",
     *   ),
     *   @SWG\Parameter(
     *      name="name",
     *      in="formData",
     *      description="姓名",
     *      required=true,
     *      type="string",
     *   ),
     *    @SWG\Parameter(
     *      name="user_id",
     *      in="formData",
     *      description="用户ID",
     *      required=true,
     *      type="integer",
     *      default="82692",
     *   ),
     *    @SWG\Parameter(
     *      name="platform",
     *      in="formData",
     *      description="三端来源",
     *      required=true,
     *      type="array",
     *      @SWG\Items(type="string"),
     *      collectionFormat="multi",
     *      default="pc",
     *      enum={"pc", "wap", "app"}
     *   ),
     *    @SWG\Parameter(
     *      name="notify_url",
     *      in="formData",
     *      description="支付成功回调地址",
     *      required=true,
     *      type="string",
     *      default="http://www.wlask.com/notify.php",
     *   ),
     *    @SWG\Parameter(
     *      name="return_url",
     *      in="formData",
     *      description="支付完成后返回的商户地址",
     *      required=true,
     *      type="string",
     *     default="http://www.wlask.com/notify.php",
     *   ),
     *   @SWG\Response(
     *     response=200,
     *     description="连连认证支付前数据加密。",
     *   )
     * )
     */
    public function encrypt(){

    }


    /**
     * @SWG\Post(
     *   path="/recharge/index?random=LLAuth_notice_decrypt",
     *   tags={"LLAuth"},
     *   summary="连连认证支付回调数据解密",
     *   @SWG\Parameter(
     *      name="partner_id",
     *      in="formData",
     *      description="商户号",
     *      required=true,
     *      type="string",
     *      default="110000901001",
     *   ),
     *    @SWG\Parameter(
     *      name="secret_sign",
     *      in="formData",
     *      description="数据校验",
     *      required=true,
     *      type="string",
     *     default="b926ab99d913f7bacbb3e526ebf75c98"
     *   ),
     *   @SWG\Parameter(
     *      name="driver",
     *      in="formData",
     *      description="支付渠道(连连认证支付)",
     *      required=true,
     *      type="string",
     *      default="LLAuth",
     *   ),
     *     @SWG\Parameter(
     *      name="method",
     *      in="formData",
     *      description="接口名称(解密)",
     *      required=true,
     *      type="string",
     *     default="decrypt",
     *   ),
     *    @SWG\Parameter(
     *      name="decrypt_type",
     *      in="formData",
     *      description="解密类型:1-notice 回调数据 2-return 支付返回数据",
     *      required=true,
     *      type="string",
     *     default="notice",
     *   ),
     *    @SWG\Parameter(
     *      name="acct_name",
     *      in="formData",
     *      description="姓名",
     *      required=true,
     *      type="string",
     *     default="刘晓蓉",
     *   ),
     *    @SWG\Parameter(
     *      name="bank_code",
     *      in="formData",
     *      description="银行编码",
     *      required=true,
     *      type="string",
     *      default="01020000",
     *   ),
     *   @SWG\Parameter(
     *      name="dt_order",
     *      in="formData",
     *      description="连连订单退款单号",
     *      required=true,
     *      type="string",
     *      default="20160602143411",
     *   ),
     *   @SWG\Parameter(
     *      name="id_no",
     *      in="formData",
     *      description="身份证号",
     *      required=true,
     *      type="string",
     *      default="362426198711080066",
     *   ),
     *    @SWG\Parameter(
     *      name="id_type",
     *      in="formData",
     *      description="证件类型",
     *      required=true,
     *      type="string",
     *      default="0",
     *   ),
     *    @SWG\Parameter(
     *      name="info_order",
     *      in="formData",
     *      description="订单信息",
     *      required=true,
     *      type="string",
     *      default="九斗鱼在线充值",
     *   ),
     *    @SWG\Parameter(
     *      name="money_order",
     *      in="formData",
     *      description="订单金额",
     *      required=true,
     *      type="string",
     *     default="0.01",
     *   ),
     *   @SWG\Parameter(
     *      name="no_agree",
     *      in="formData",
     *      description="no_agree",
     *      required=true,
     *      type="string",
     *     default="2016060270323498",
     *   ),
     *   @SWG\Parameter(
     *      name="no_order",
     *      in="formData",
     *      description="订单号",
     *      required=true,
     *      type="string",
     *     default="JDY_201606020634114999",
     *   ),
     *     @SWG\Parameter(
     *      name="oid_partner",
     *      in="formData",
     *      description="商户号",
     *      required=true,
     *      type="string",
     *     default="201409121000024506",
     *   ),
     *     @SWG\Parameter(
     *      name="oid_paybill",
     *      in="formData",
     *      description="交易流水号",
     *      required=true,
     *      type="string",
     *     default="2016060267033257",
     *   ),
     *     @SWG\Parameter(
     *      name="pay_type",
     *      in="formData",
     *      description="pay_type",
     *      required=true,
     *      type="string",
     *     default="D",
     *   ),
     *     @SWG\Parameter(
     *      name="result_pay",
     *      in="formData",
     *      description="支付状态",
     *      required=true,
     *      type="string",
     *     default="SUCCESS",
     *   ),
     *     @SWG\Parameter(
     *      name="settle_date",
     *      in="formData",
     *      description="支付日期",
     *      required=true,
     *      type="string",
     *     default="20160602",
     *   ),
     *     @SWG\Parameter(
     *      name="sign",
     *      in="formData",
     *      description="验签",
     *      required=true,
     *      type="string",
     *     default="e4b5ec70b504429db0f41b2de06732b8",
     *   ),
     *     @SWG\Parameter(
     *      name="sign_type",
     *      in="formData",
     *      description="加密类型",
     *      required=true,
     *      type="string",
     *     default="MD5",
     *   ),
     *   @SWG\Response(
     *     response=200,
     *     description="连连认证支付完成后的回调数据解密。",
     *   )
     * )
     */
    public function decryptNotice(){}



    /**
     * @SWG\Post(
     *   path="/recharge/index?random=LLAuth_return_decrypt",
     *   tags={"LLAuth"},
     *   summary="连连认证支付返回数据解密",
     *   @SWG\Parameter(
     *      name="partner_id",
     *      in="formData",
     *      description="商户号",
     *      required=true,
     *      type="string",
     *      default="110000901001",
     *   ),
     *    @SWG\Parameter(
     *      name="secret_sign",
     *      in="formData",
     *      description="数据校验",
     *      required=true,
     *      type="string",
     *     default="b926ab99d913f7bacbb3e526ebf75c98"
     *   ),
     *   @SWG\Parameter(
     *      name="driver",
     *      in="formData",
     *      description="支付渠道(连连认证支付)",
     *      required=true,
     *      type="string",
     *      default="LLAuth",
     *   ),
     *     @SWG\Parameter(
     *      name="method",
     *      in="formData",
     *      description="接口名称(解密)",
     *      required=true,
     *      type="string",
     *     default="decrypt",
     *   ),
     *    @SWG\Parameter(
     *      name="decrypt_type",
     *      in="formData",
     *      description="解密类型:1-notice 回调数据 2-return 支付返回数据",
     *      required=true,
     *      type="string",
     *     default="return",
     *   ),
     *    @SWG\Parameter(
     *      name="bank_code",
     *      in="formData",
     *      description="银行编码",
     *      required=true,
     *      type="string",
     *      default="03080000",
     *   ),
     *   @SWG\Parameter(
     *      name="dt_order",
     *      in="formData",
     *      description="连连订单退款单号",
     *      required=true,
     *      type="string",
     *      default="20160604131653",
     *   ),
     *    @SWG\Parameter(
     *      name="info_order",
     *      in="formData",
     *      description="订单信息",
     *      required=true,
     *      type="string",
     *      default="九斗鱼在线充值",
     *   ),
     *    @SWG\Parameter(
     *      name="money_order",
     *      in="formData",
     *      description="订单金额",
     *      required=true,
     *      type="string",
     *     default="1.00",
     *   ),
     *   @SWG\Parameter(
     *      name="no_order",
     *      in="formData",
     *      description="订单号",
     *      required=true,
     *      type="string",
     *     default="JDY_201606041316533538",
     *   ),
     *   @SWG\Parameter(
     *      name="settle_date",
     *      in="formData",
     *      description="订单日期",
     *      required=true,
     *      type="string",
     *     default="20160604",
     *   ),
     *     @SWG\Parameter(
     *      name="oid_partner",
     *      in="formData",
     *      description="商户号",
     *      required=true,
     *      type="string",
     *     default="201409121000024506",
     *   ),
     *     @SWG\Parameter(
     *      name="oid_paybill",
     *      in="formData",
     *      description="交易流水号",
     *      required=true,
     *      type="string",
     *     default="2016060473113741",
     *   ),
     *     @SWG\Parameter(
     *      name="pay_type",
     *      in="formData",
     *      description="pay_type",
     *      required=true,
     *      type="string",
     *     default="D",
     *   ),
     *     @SWG\Parameter(
     *      name="result_pay",
     *      in="formData",
     *      description="支付状态",
     *      required=true,
     *      type="string",
     *     default="SUCCESS",
     *   ),
     *     @SWG\Parameter(
     *      name="sign",
     *      in="formData",
     *      description="验签",
     *      required=true,
     *      type="string",
     *     default="b926ab99d913f7bacbb3e526ebf75c98",
     *   ),
     *     @SWG\Parameter(
     *      name="sign_type",
     *      in="formData",
     *      description="加密类型",
     *      required=true,
     *      type="string",
     *     default="MD5",
     *   ),
     *   @SWG\Response(
     *     response=200,
     *     description="连连认证支付完成后的返回数据解密。",
     *   ),
     *   @SWG\Response(
     *     response="500",
     *     description="失败状态,存在参数的缺失.",
     *   )
     * )
     */
    public function decryptReturn(){}



    /**
     * @SWG\Post(
     *   path="/recharge/index?random=LLAuth_search",
     *   tags={"LLAuth"},
     *   summary="连连认证支付主动查单",
     *   @SWG\Parameter(
     *      name="partner_id",
     *      in="formData",
     *      description="商户号",
     *      required=true,
     *      type="string",
     *      default="110000901001",
     *   ),
     *    @SWG\Parameter(
     *      name="secret_sign",
     *      in="formData",
     *      description="数据校验",
     *      required=true,
     *      type="string",
     *     default="b926ab99d913f7bacbb3e526ebf75c98"
     *   ),
     *   @SWG\Parameter(
     *      name="driver",
     *      in="formData",
     *      description="支付渠道(连连认证支付)",
     *      required=true,
     *      type="string",
     *      default="LLAuth",
     *   ),
     *     @SWG\Parameter(
     *      name="method",
     *      in="formData",
     *      description="接口名称(查单)",
     *      required=true,
     *      type="string",
     *     default="search",
     *   ),
     *   @SWG\Parameter(
     *      name="order_id",
     *      in="formData",
     *      description="查询订单号",
     *      required=true,
     *      type="string",
     *      default="JDY_201606041316533538",
     *   ),

     *   @SWG\Response(
     *     response=200,
     *     description="连连认证支付主动查单,有IP白名单的限制,本地无法请求。",
     *   )
     * )
     */
    public function search(){}
    



}