<?php
/**
 * Created by PhpStorm.
 * User: zhangshuang
 * Date: 16/6/4
 * Time: 11:26
 */
namespace App\Http\Controllers\Swagger\Pay;

class ReaWithholding{

    /**
     * @SWG\Post(
     *   path="/recharge/index?random=ReaWithholding_signed",
     *   tags={"ReaWithholding"},
     *   summary="融宝代扣验卡",
     *   @SWG\Parameter(
     *      name="partner_id",
     *      in="formData",
     *      description="商户号",
     *      required=true,
     *      type="string",
     *      default="110000901001",
     *   ),
     *    @SWG\Parameter(
     *      name="secret_sign",
     *      in="formData",
     *      description="数据校验",
     *      required=true,
     *      type="string",
     *     default="b926ab99d913f7bacbb3e526ebf75c98"
     *   ),
     *   @SWG\Parameter(
     *      name="driver",
     *      in="formData",
     *      description="支付渠道(融宝代扣)",
     *      required=true,
     *      type="string",
     *      default="ReaWithholding",
     *   ),
     *   @SWG\Parameter(
     *      name="method",
     *      in="formData",
     *      description="接口名称(签约)",
     *      required=true,
     *      type="string",
     *     default="signed",
     *   ),
     *   @SWG\Parameter(
     *      name="card_no",
     *      in="formData",
     *      description="银行卡号",
     *      required=true,
     *      type="string",
     *   ),
     *   @SWG\Parameter(
     *      name="id_card",
     *      in="formData",
     *      description="身份证号",
     *      required=true,
     *      type="string",
     *   ),
     *   @SWG\Parameter(
     *      name="phone",
     *      in="formData",
     *      description="手机号",
     *      required=true,
     *      type="string",
     *   ),
     *   @SWG\Parameter(
     *      name="order_id",
     *      in="formData",
     *      description="订单编号",
     *      required=true,
     *      type="string",
     *   ),
     *   @SWG\Parameter(
     *      name="cash",
     *      in="formData",
     *      description="充值金额",
     *      required=true,
     *      type="integer",
     *   ),
     *   @SWG\Parameter(
     *      name="name",
     *      in="formData",
     *      description="姓名",
     *      required=true,
     *      type="string",
     *  ),
     *  @SWG\Parameter(
     *      name="user_id",
     *      in="formData",
     *      description="用户ID",
     *      required=true,
     *      type="integer",
     *      default="82692",
     *   ),
     *  @SWG\Parameter(
     *      name="notify_url",
     *      in="formData",
     *      description="支付成功回调地址",
     *      required=true,
     *      type="string",
     *      default="http://www.wlask.com/notify.php",
     *   ),
     *   @SWG\Response(
     *     response=200,
     *     description="融宝代扣签约。",
     *   )
     * )
     */
    public function signed(){}

    /**
     * @SWG\Post(
     *   path="/recharge/index?random=ReaWithholding_sendCode",
     *   tags={"ReaWithholding"},
     *   summary="融宝代扣发送验证码",
     *   @SWG\Parameter(
     *      name="partner_id",
     *      in="formData",
     *      description="商户号",
     *      required=true,
     *      type="string",
     *      default="110000901001",
     *   ),
     *    @SWG\Parameter(
     *      name="secret_sign",
     *      in="formData",
     *      description="数据校验",
     *      required=true,
     *      type="string",
     *     default="b926ab99d913f7bacbb3e526ebf75c98"
     *   ),
     *   @SWG\Parameter(
     *      name="driver",
     *      in="formData",
     *      description="支付渠道(融宝代扣)",
     *      required=true,
     *      type="string",
     *      default="ReaWithholding",
     *   ),
     *   @SWG\Parameter(
     *      name="method",
     *      in="formData",
     *      description="接口名称(发送验证码)",
     *      required=true,
     *      type="string",
     *     default="sendCode",
     *   ),
     *   @SWG\Parameter(
     *      name="order_id",
     *      in="formData",
     *      description="订单编号",
     *      required=true,
     *      type="string",
     *   ),

     *   @SWG\Response(
     *     response=200,
     *     description="融宝代扣发送验证码。",
     *   )
     * )
     */
    public function sendCode(){}


    /**
     * @SWG\Post(
     *   path="/recharge/index?random=ReaWithholding_submit",
     *   tags={"ReaWithholding"},
     *   summary="融宝代扣提交支付",
     *   @SWG\Parameter(
     *      name="partner_id",
     *      in="formData",
     *      description="商户号",
     *      required=true,
     *      type="string",
     *      default="110000901001",
     *   ),
     *    @SWG\Parameter(
     *      name="secret_sign",
     *      in="formData",
     *      description="数据校验",
     *      required=true,
     *      type="string",
     *     default="b926ab99d913f7bacbb3e526ebf75c98"
     *   ),
     *   @SWG\Parameter(
     *      name="driver",
     *      in="formData",
     *      description="支付渠道(钱袋宝代扣)",
     *      required=true,
     *      type="string",
     *      default="ReaWithholding",
     *   ),
     *   @SWG\Parameter(
     *      name="method",
     *      in="formData",
     *      description="接口名称(提交支付)",
     *      required=true,
     *      type="string",
     *     default="submit",
     *   ),
     *    @SWG\Parameter(
     *      name="order_id",
     *      in="formData",
     *      description="订单编号",
     *      required=true,
     *      type="string",
     *   ),
     *   @SWG\Parameter(
     *      name="sms_code",
     *      in="formData",
     *      description="短信验证码",
     *      required=true,
     *      type="string",
     *   ),
     *   @SWG\Response(
     *     response=200,
     *     description="融宝支付。",
     *   )
     * )
     */
    public function submit(){}

    /**
     * @SWG\Post(
     *   path="/recharge/index?random=ReaWithholding_decrypt",
     *   tags={"ReaWithholding"},
     *   summary="钱袋宝代扣回调数据解密",
     *   @SWG\Parameter(
     *      name="partner_id",
     *      in="formData",
     *      description="商户号",
     *      required=true,
     *      type="string",
     *      default="110000901001",
     *   ),
     *    @SWG\Parameter(
     *      name="secret_sign",
     *      in="formData",
     *      description="数据校验",
     *      required=true,
     *      type="string",
     *     default="b926ab99d913f7bacbb3e526ebf75c98"
     *   ),
     *   @SWG\Parameter(
     *      name="driver",
     *      in="formData",
     *      description="支付渠道(融宝代扣)",
     *      required=true,
     *      type="string",
     *      default="ReaWithholding",
     *   ),
     *   @SWG\Parameter(
     *      name="method",
     *      in="formData",
     *      description="接口名称(解密)",
     *      required=true,
     *      type="string",
     *     default="decrypt",
     *   ),
     *    @SWG\Parameter(
     *      name="data",
     *      in="formData",
     *      description="回调返回的加密数据",
     *      required=true,
     *      type="string",
     *     default="vrBox3sIx0i3jiGL4c6FVOyDtk/NwAbHp+3Djvu7mEIeVd/5jFxWBgelnQ0esGuruZw/QnloIsdhJr7mY4hJT3QdavO+bJefROx7ox/GGD/V0+8X9GcpchRNukFYWd8t1oUibThSMiFVLhwMCWZdnlrgDUcQX9eB/xfq3I055uFTc44NAZv213gjGJcnAkMdPP9ZIfI0NCTnH9RyXOB8yGdqT8LSzYdvI1kIfyEaqmbJN6Gv/2rQZ8PqtnY9jdd3spUrEJ+1bPLo4K/0JJ8Xdw==",
     *   ),
     *   @SWG\Parameter(
     *      name="encryptkey",
     *      in="formData",
     *      description="加密KEY",
     *      required=true,
     *      type="string",
     *     default="ml1M9SG68n+DoCdeASvxTSTFXVOqVZYfFFGahy5GxN9p819eCNsyumAQTox8Nf+bxOmpDo7OENJXkNPNOcJ2fbUfNg4E2JMIibcJUSizL6f8zdbzBTOl5CAm8QWTMgYKohubMMDCjfOMAPVavI4JOS8Ss/Yzo7BxF9BAq5NECw8",
     *   ),
     *   @SWG\Parameter(
     *      name="merchant_id",
     *      in="formData",
     *      description="商户号",
     *      required=true,
     *      type="string",
     *     default="100000001300212"
     *   ),
     *   @SWG\Response(
     *     response=200,
     *     description="融宝回调解密。",
     *   )
     * )
     */
    public function decrypt(){}

    /**
     * @SWG\Post(
     *   path="/recharge/index?random=ReaWithholding_search",
     *   tags={"ReaWithholding"},
     *   summary="融宝代扣主动查单",
     *   @SWG\Parameter(
     *      name="partner_id",
     *      in="formData",
     *      description="商户号",
     *      required=true,
     *      type="string",
     *      default="110000901001",
     *   ),
     *    @SWG\Parameter(
     *      name="secret_sign",
     *      in="formData",
     *      description="数据校验",
     *      required=true,
     *      type="string",
     *     default="b926ab99d913f7bacbb3e526ebf75c98"
     *   ),
     *    @SWG\Parameter(
     *      name="driver",
     *      in="formData",
     *      description="支付渠道(融宝代扣)",
     *      required=true,
     *      type="string",
     *      default="ReaWithholding",
     *   ),
     *   @SWG\Parameter(
     *      name="method",
     *      in="formData",
     *      description="接口名称(查单)",
     *      required=true,
     *      type="string",
     *     default="search",
     *   ),
     *   @SWG\Parameter(
     *      name="order_id",
     *      in="formData",
     *      description="查询订单号",
     *      required=true,
     *      type="string",
     *      default="",
     *   ),
     *   @SWG\Response(
     *     response=200,
     *     description="融宝代扣主动查单。",
     *   )
     * )
     */
    public function search(){}
}